<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.9.13</Version>
    <AssemblyVersion>1.9.13.0</AssemblyVersion>
    <FileVersion>1.9.13.0</FileVersion>
    <InformationalVersion>1.9.13</InformationalVersion>
  </PropertyGroup>

</Project>
