<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.15.20</Version>
    <AssemblyVersion>1.15.20.0</AssemblyVersion>
    <FileVersion>1.15.20.0</FileVersion>
    <InformationalVersion>1.15.20</InformationalVersion>
  </PropertyGroup>
</Project>
